name: 'Action Name'
description: 'Action Description'

inputs:
  aws-role-arn:
    description: Arn of the role to be assumed.
    required: true
    default: arn:aws:iam::111122223333:role/github-oidc-role
    type: string
  aws-region:
    description: AWS region where the services will be deployed
    required: true
    default: us-east-1
    type: string
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials from AWS account
      id: aws-config
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: github-aws-cloudformation-oidc

    - name: Debug - Check the available files
      run: |
        cd ${{ github.workspace }}
        ls -lR
        
    - name: Test AWS CLI
      id: test-aws-cli
      run: |
        aws s3 ls

    # - name: Configure OIDC      
    #   shell: bash
    #   env:
    #     GITHUB_TOKEN: ${{ inputs.github-token }}
    #   run: |
    #     echo "Hello World !"
        # ISSUE_NUMBER="${{ github.event.issue.number }}"
        # REPO="${{ github.repository }}"
        # OWNER=$(echo $REPO | cut -d'/' -f1)
        # BRANCH_NAME="${{ steps.create-branch.outputs.branch-name }}"
        # COMMENT_BODY="Branch [$BRANCH_NAME](https://github.com/$OWNER/$REPO/tree/$BRANCH_NAME) created 🚀"

        # curl -s -X POST \
        #   -H "Authorization: token $GITHUB_TOKEN" \
        #   -H "Content-Type: application/json" \
        #   -d "{\"body\": \"$COMMENT_BODY\"}" \
        #   https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments
