name: 'Scan and Validate'
description: 'Scan and Validate IAC Template'

inputs:
  aws-role-arn:
    description: "Arn of the role to be assumed. (e.g., arn:aws:iam::111122223333:role/github-oidc-role)"
    required: true
    default: "arn:aws:iam::111122223333:role/github-oidc-role"
  aws-region:
    description: "AWS region where the services will be deployed (e.g., us-east-1)"
    required: true
    default: "us-east-1"
  template-dir:
    description: "The directory path of the IAC file."
    required: true
    default: "cfn"
  template-file:
    description: "The IAC template file name."
    required: true
    default: "root-stack-template.yaml"
  iac-framework:
    description: "IAC Framework - Accepted values: cloudformation, terraform, kubernetes, all"
    required: true
    default: "cloudformation"
  soft-fail:
    description: "If true, Checkov scan will not fail the pipeline"
    required: true
    default: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials from AWS account
      id: aws-config
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: github-aws-cloudformation-oidc

    - name: Run CloudFormation Validate
      id: validate-cfn
      if: ${{ inputs.iac-framework == 'cloudformation' }}
      shell: bash
      run: |
        echo "Validating CloudFormation template..."
    
        # Run the validation, capture both stdout and stderr
        VALIDATION_OUTPUT=$(aws cloudformation validate-template \
          --template-body file://${{ github.workspace }}/${{ inputs.template-dir }}/${{ inputs.template-file }} 2>&1)
        STATUS=$?
    
        echo "Raw output:"
        echo "$VALIDATION_OUTPUT"
    
        # Check if the validation passed
        if [ $STATUS -eq 0 ]; then
          DESCRIPTION=$(echo "$VALIDATION_OUTPUT" | jq -r '.Description // "No description available"')
          echo "Validation passed. Description: $DESCRIPTION"
        else
          DESCRIPTION="Validation failed"
          echo "Validation failed. Output:"
          echo "$VALIDATION_OUTPUT"
        fi
    
        # Export outputs
        echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
        echo "raw_output=$VALIDATION_OUTPUT" >> $GITHUB_OUTPUT
        echo "success=$([ $STATUS -eq 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT



    - name: Run Checkov Scan
      if: always()
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ github.workspace }}/${{ inputs.template-dir }}
        soft_fail: ${{ inputs.soft-fail }}
        quiet: true
        framework: ${{ inputs.iac-framework }}
